name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
workers_dev = false

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8888


[env.dev.vars]

[env.production]
name = "d"
routes = [
  { pattern = "d.hii.us.kg", custom_domain = true }
]

[env.production.vars]
MODE = "production"

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
